### ISSUE TITLE
Login data does not persist after client is closed

### ISSUE THREAD

**Issue by nrichw-eta** [stig-atle/YarnDesktopClient#11]
OS: EndeavourOS Cassini Nova (w/ linux kernel 6.2.11)

It's not a dealbreaker but huge QOL feature would be to have the option to have login data persist from session to session.

**Comment by stig-atle** [comment]
I fully agree. I just need to figure out how I can store it securely - what API or tool to use for that.
I also thought about something today - maybe we do not need to log in as often as long as the token is valid.
I'll ask about that on yarn - how often \ why the token changes. That way we can skip the login if token is still valid,
then present the login screen if the token is invalid. And then as you say - also store the entered password.

**Comment by stig-atle** [comment]
I'm working on this now. I use libsecret, got storage to work, just need retrieval and it's done.
I'll update the readme with package info as well when I'm done.

**Comment by stig-atle** [comment]
Pushed a fix for this now.
